### ISSUE TITLE
World crashes on join due to cast error.

### ISSUE THREAD

**Issue by EliteAsian123** [raoulvdberge/refinedpipes#7]
Full error:
```
java.lang.ClassCastException: com.raoulvdberge.refinedpipes.network.pipe.energy.EnergyPipe cannot be cast to com.raoulvdberge.refinedpipes.network.pipe.item.ItemPipe
	at com.raoulvdberge.refinedpipes.network.pipe.Pipe.equals(Pipe.java:90) ~[?:0.4] {re:classloading}
	at java.util.HashMap.putVal(HashMap.java:634) ~[?:1.8.0_51] {}
	at java.util.HashMap.put(HashMap.java:611) ~[?:1.8.0_51] {}
	at java.util.HashSet.add(HashSet.java:219) ~[?:1.8.0_51] {}
	at com.raoulvdberge.refinedpipes.network.graph.NetworkGraphScanner.singleScanAt(NetworkGraphScanner.java:61) ~[?:0.4] {re:classloading}
	at com.raoulvdberge.refinedpipes.network.graph.NetworkGraphScanner.scanAt(NetworkGraphScanner.java:41) ~[?:0.4] {re:classloading}
	at com.raoulvdberge.refinedpipes.network.graph.NetworkGraph.scan(NetworkGraph.java:25) ~[?:0.4] {re:classloading}
	at com.raoulvdberge.refinedpipes.network.Network.scanGraph(Network.java:36) ~[?:0.4] {re:classloading}
	at com.raoulvdberge.refinedpipes.network.energy.EnergyNetwork.scanGraph(EnergyNetwork.java:32) ~[?:0.4] {re:classloading}
	at com.raoulvdberge.refinedpipes.network.Network.update(Network.java:54) ~[?:0.4] {re:classloading}
	at com.raoulvdberge.refinedpipes.network.energy.EnergyNetwork.update(EnergyNetwork.java:55) ~[?:0.4] {re:classloading}
	at com.raoulvdberge.refinedpipes.setup.CommonSetup.lambda$onWorldTick$13(CommonSetup.java:151) ~[?:0.4] {re:classloading}
	at com.raoulvdberge.refinedpipes.setup.CommonSetup$$Lambda$16586/639785258.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap$Values.forEach(HashMap.java:972) ~[?:1.8.0_51] {}
	at com.raoulvdberge.refinedpipes.setup.CommonSetup.onWorldTick(CommonSetup.java:151) ~[?:0.4] {re:classloading}
	at com.raoulvdberge.refinedpipes.RefinedPipes$$Lambda$4226/1191719350.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2107/826045717.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:99) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world/MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world/MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world/MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}
```
I have no idea what caused this to happen. I can no longer join my world, as it crashes every time due to the same error.

Crash Log:
https://pastebin.com/7qaz2APb

Thanks!

**Comment by Soneliver** [comment]
i have a same error... if you have found a tips ?

**Comment by EliteAsian123** [comment]
I've tried multiple things, none of which worked. Only uninstalling the mod let me join the world.

**Comment by Soneliver** [comment]
I have send with crash report, on the discord dev I wait for see...

**Comment by raoulvdberge** [comment]
This has been fixed.

**Comment by raoulvdberge** [comment]
https://github.com/raoulvdberge/refinedpipes/commit/f82fdd290c99fd1659f1c0b82547e7076fe163e8
